### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by psteinb** [sdsc/sdsc-summer-institute-2019#54]
Hi,
Thanks for sharing these educational resources. Is this material published under a specific license?
Best,
P

**Comment by zonca** [comment]
@sinkovit I think we should publish under https://creativecommons.org/licenses/by-nc-sa/4.0/

@psteinb would such license fit your purpose?

**Comment by sinkovit** [comment]
Hi Andrea,

I read the overview of the Creative Commons license and this looks appropriate. Let’s go with it.

-- Bob

**Comment by zonca** [comment]
thanks @sinkovit 
I asked all the instructors to check they agree, we will most probably proceed with this within 1 week.

**Comment by zonca** [comment]
thanks @psteinb for pointing to this, we not got both a license and a DOI, see the README.
