### ISSUE TITLE
sbatch: error: Batch job submission failed: Socket timed out on send/recv operation

### ISSUE THREAD

**Issue by Shicheng-Guo** [sdsc/sdsc-summer-institute-2019#55]
Always meet the situations as the below when using bash loop to submit hundreds jobs. Any suggestion? 
```
sbatch: error: Batch job submission failed: Socket timed out on send/recv operation
Submitted batch job 3310326
Submitted batch job 3310327
Submitted batch job 3310328
Submitted batch job 3310329
Submitted batch job 3310330
Submitted batch job 3310331
Submitted batch job 3310332
Submitted batch job 3310333
Submitted batch job 3310334
Submitted batch job 3310335
Submitted batch job 3310336
Submitted batch job 3310337
Submitted batch job 3310338
Submitted batch job 3310339
Submitted batch job 3310340
Submitted batch job 3310341
Submitted batch job 3310342
sbatch: error: Batch job submission failed: Socket timed out on send/recv operation
Submitted batch job 3310344
Submitted batch job 3310347
```

**Comment by mahidhar** [comment]
Shicheng,

Please send issues to the ticketing system. This is an old Summer Institute GitHub site and not the right place for these sort of questions. I will reply to you directly regarding the issue.

Mahidhar

**Comment by jgbaum** [comment]
Hi @Shicheng-Guo and @mahidhar,

We are running into the very same issue on our newly installed slurm cluster and can't find much useful information about this on the web.  We've noticed that even though sbatch reports an error and does not return a job ID, the job still gets submitted and sbatch exits with a 0 exit code.  This is problematic for many of our pipelines that we with to migrate from torque to slurm.

 If you have resolved this, or can help point us to someone who might be able to assist, that would be much appreciated.

Thanks!

-Jason
